[tool.pytest.ini_options]
addopts = """\
          --strict-markers \
          --ignore-glob */backends/test_database.py \
          --ignore-glob */backends/test_mongodb.py \
          """
testpaths = "t/unit/"
python_classes = "test_*"
xdfail_strict=true
markers = ["sleepdeprived_patched_module", "masked_modules", "patched_environ", "patched_module"]
